FileUtils: MSVC-specific wstring fstream ctor
PDAL/PDAL pull request #3507
Opened 2021-08-06 19:30 UTC by xantares

2021-08-06 19:57 UTC, hobu commented
This will not be merged without tests that exercise it.

2021-08-06 20:09 UTC, xantares commented
The msvc code-path stays the same, this only enables build for mingw.

2021-08-06 21:31 UTC, abellgithub commented
I'm not inclined to make these changes as such. _MSC_VER is a *compiler version*, not an operating system tag. There has been *limited* interest in mingw before, but I'm not sure there's enough demand to take on the support burden. Rather than just submit a bunch of PRs, some discussion how/if this should be best handled.

2021-08-06 21:38 UTC, xantares commented
yes, these changes are meant to allow compilation with the mingw compiler which, like msvc also targets win32
and there are some differences between the two, mingw tends to stick to standards but also sometimes does not fully cover the win32 apis

I thought the PR path is ok as most changes are minimal, how do you propose we proceed then ?

2021-08-06 22:21 UTC, hobu commented
Are all of these changes in support of an open source project or something? While we can merge many of them, without a mingw CI platform, they're just going to rot again.

2021-08-06 22:27 UTC, xantares commented
yes I wanted to try building qgis
if this is accepted maybe I can setup a ci job

2021-08-06 22:31 UTC, hobu commented
Is mingw the supported build path for QGIS @wonder-sk? 

> if this is accepted maybe I can setup a ci job

It's the other way. For us to merge all this stuff, we want a mingw builder. Otherwise it is just going to rot, and we don't know how to test it or make it work. Without any of that stuff, it is just more code to break and maintain.

2021-08-07 00:00 UTC, abellgithub commented
Why would one want a mingw build of QGIS when native windows builds exist?

2021-08-07 00:14 UTC, giordano commented
Someone already [tried to answer](https://github.com/PDAL/PDAL/issues/3329#issuecomment-779357313).

2021-08-07 00:30 UTC, abellgithub commented
Right, but I think we're talking about a project that already has Windows and *nix CI and development support.

2021-08-07 00:44 UTC, Keno commented
The question here is not as much mingw vs MSVC or Windows vs non-Windows as it is libc++ or GNU libstdc++ vs Microsoft STL, since the latter has a proprietary extension here. gcc only works with the former, MSVC only with the latter, but there are compilers that's support both. Which one you want depends on the platform choice of your host application. For example over at julialang.org (which @giordano is supporting), our windows builds are standardized to libstdc++, so anybody wanting to use this library with Julia will require this patch or an equivalent (which we currently carry locally). Now, it would be nice if there was a preprocessor define to detect the std library independent of the compiler, but there currently isn't. Not that this isn't a problem in practice, since compilers that support both actually do set `_MSC_VER` when targeting the MS STL, even if they're not MSVC, so this patch is correct. We've in the past considered offering upstream CI with our build configurations, since we support a lot of them (> 30) that often upstream developers don't have access to, but unfortunately we're not yet in a position to do so. Still, merging this patch would be useful since it would mean support for libstdc++ standardized applications without extra patches.

2021-08-07 02:27 UTC, hobu commented
Our primary concern with all of these patches is being put on the hook to support a configuration we do not currently support on a platform that is not currently tested. That concern goes away if there's a CI that tests this configuration and platform.

I'm sympathetic to wanting to have these patches be upstreamed, and we're not trying to be intransigent, but a blizzard of drive-by PRs with little context, no promise of future support, no linkage to a downstream issue, or lack of demonstration of a bug doesn't engender enthusiasm to maintain this forever. If @xantares declares themselves forever the mingw maintainer and a CI worker is built that highlights when we should nag them to fix it 😄, we don't have any issue with this stuff. 

Blindly merging stuff that has the potential to break stuff we know to work in the configurations we currently support makes us nervous.

2021-08-07 10:58 UTC, xantares commented
For the configurations you already support I suppose it's already well tested, I see CI and everything, so it should be fine.
For mingw usually these platforms quirks are very low maintenance, and dependencies, flags etc dont change often.

2021-08-08 12:27 UTC, hobu requested changes
Reviewing the actual content of the PR, this represents a behavior change. The patch should be to `toNative` instead of splatting an `#ifdef` right here. `toNative` is used in many other places.

2021-08-09 08:26 UTC, wonder-sk commented
> Is mingw the supported build path for QGIS @wonder-sk?

Apparently yes since ~Feb 2021, there is a mingw build in qgis CI:
https://github.com/qgis/QGIS/blob/master/.github/workflows/mingw64.yml
But that build does not include PDAL
https://github.com/qgis/QGIS/blob/master/ms-windows/mingw/build.sh

But on windows, only MSVC builds of QGIS are the ones shipped to users.

2021-08-09 11:47 UTC, xantares commented
I came with another solution: we enable c++17 on mingw with pdalboost::filesystem as an alias to std::filesystem.
Eventually it will allow to drop boost completely when the oldest supported version of msvc allows it (currently it seems to be vs2015/c++11).

2021-09-08 17:12 UTC, abellgithub commented
Believe this should be fixed with #3536

2021-09-08 17:12 UTC, closed without merging