Add read/write fbi format
PDAL/PDAL pull request #3654
Opened 2022-01-13 14:01 UTC by alavenant

Code for read and write Fbi format. 
TerrasScan use fbi format internaly to manipulate points clouds.

2022-01-13 20:36 UTC, hobu requested changes
This is great! Thanks for the contribution! A few small comments, it will need some docs, and a small tweak to the test config will help it fit with other format drivers. We will plan to include this in PDAL 2.4 if it can be cleaned up in the next few weeks.

2022-01-13 20:36 UTC, hobu commented on io/FbiReader.cpp
> +     Other Fbi contents - Not found equivalent in pdal model for now
It would be reasonable to make add PDAL dimensions for these.

2022-01-13 20:36 UTC, hobu commented on io/FbiReader.cpp
> +    "http://pdal.io/stages/readers.fbi.html", // _ToDo_
We will need a doc to merge this.

2022-01-13 20:36 UTC, hobu commented on io/FbiWriter.cpp
> +        "http://pdal.io/stages/writers.fbi.html"
need a doc

2022-01-13 20:36 UTC, hobu commented on test/unit/io/FbiReaderTest.cpp
> +    return Support::datapath("fbi/test.fbi");
Can you write the `1.2-with-color.las` file to fbi, add it to the test suite, and add a simple test that checks coordinates or intensity or something? This provides commonly tested values for various formats so we have some context when looking at transformed data.

2022-01-14 20:30 UTC, abellgithub reviewed
General:

All this seems to assume you're running on a little-endian machine. This is pretty-much always the case these days, but if you're not going to support big-endian, you should probably throw an error if someone tries to use it on BE.

2022-07-25 20:21 UTC, hobu commented
Moved over to #3822 so I can push and finish this up. Thanks for the contribution!

2022-07-25 20:21 UTC, closed without merging