TIndexKernel file creation - multithreaded
PDAL/PDAL pull request #4531
Opened 2024-10-22 15:12 UTC by ibell13

Added support for running the point reading and boundary creation stages in multiple threads when creating a tile index. Also implemented a custom filter stage that creates _filters.hexbin_ boundaries in a stripped-down and thread safe way. Settings for the TIndexKernel boundary filter are now directly specified with tindex args rather than requiring the user to set options for filters.hexbin.

2024-10-22 15:47 UTC, hobu requested changes

2024-10-22 15:47 UTC, hobu commented on kernels/TIndexKernel.cpp
> +std::string TIndexKernel::makeMultiPolygon(const std::string& wkt)
😬

2024-10-22 15:47 UTC, hobu commented on kernels/TIndexKernel.hpp
> +namespace hexer
why do we need this forward declaration if we're also including the `HexGrid.hpp` header?

2024-10-22 15:47 UTC, hobu commented on kernels/TIndexKernel.cpp
> +        args.add("threads", "Number of threads to use for file boundary creation",
Maybe we should add a `requests` synonym here too.

2024-10-22 15:47 UTC, hobu commented on kernels/TIndexKernel.cpp
> +        args.add("smooth", "Smooth boundary output", m_doSmooth, true);
Maybe this should be more accurately called `simplify`?

2024-10-22 15:47 UTC, hobu commented on kernels/TIndexKernel.cpp
> +        args.add("threshold", "Required cell density, to be used in internal "
`Number of points a cell must contain to be declared positive space`

2024-10-22 15:47 UTC, hobu commented on kernels/TIndexKernel.cpp
> +        args.add("edge_length", "cell edge length to be used in internal hexbin "
This is really a `resolution`, and I think we should call it that.

2024-10-22 15:47 UTC, hobu commented on kernels/TIndexKernel.cpp
> +        args.add("sample_size", "Sample size for auto-edge length calculation in "
Do we have to expose this to users? They can do `--filters.hexbin.sample_size` themselves if they want.

2024-10-22 15:47 UTC, hobu commented on kernels/TIndexKernel.cpp
> +        double tolerance = 1.1 * fileInfo.m_gridHeight / 2;
where did this magic come from?

2024-10-25 15:11 UTC, ibell13 commented on kernels/TIndexKernel.cpp
> +    virtual void spatialReferenceChanged(const SpatialReference& srs)
If I do Stage::getSpatialReference() on the filter stage without setting it explicitly, the SRS is empty. But maybe there's a different/better way to set it.

2024-10-25 15:18 UTC, abellgithub commented on kernels/TIndexKernel.cpp
> +    virtual void spatialReferenceChanged(const SpatialReference& srs)
Yes, I forgot it was being extracted in the FileInfo.

2024-11-15 20:21 UTC, hobu approved these changes

2024-11-15 20:22 UTC, merged